=== RalfSchmelter/EasySok/res/themes/easysoktheme.dtd
<!ELEMENT EasySokTheme ( ( KeeperOnFloor | ( LeftKeeperOnFloor, RightKeeperOnFloor, UpKeeperOnFloor, 
					     DownKeeperOnFloor ) ),
			  ( KeeperOnDeadFloor | ( LeftKeeperOnDeadFloor, RightKeeperOnDeadFloor, 
						  UpKeeperOnDeadFloor, DownKeeperOnDeadFloor ) ),
 			  ( KeeperOnGoal | ( LeftKeeperOnGoal, RightKeeperOnGoal, UpKeeperOnGoal,
					     DownKeeperOnGoal ) ),
			  ( MovingKeeper | ( LeftMovingKeeper, RightMovingKeeper, UpMovingKeeper,
					     DownMovingKeeper ) ),
			  ( VirtualKeeper | ( LeftVirtualKeeper, RightVirtualKeeper, UpVirtualKeeper,
					      DownVirtualKeeper) ),
			GemOnFloor, GemOnDeadFloor, GemOnGoal, MovingGem, Floor, DeadFloor, Goal,
			LeftArrow, RightArrow, UpArrow, DownArrow, Wall, Outside) >
<!ATTLIST EasySokTheme
  name CDATA #REQUIRED
  leftborder CDATA #IMPLIED
  rightborder CDATA #IMPLIED
  upperborder CDATA #IMPLIED
  lowerborder CDATA #IMPLIED
  red CDATA #IMPLIED
  green CDATA #IMPLIED
  blue CDATA #IMPLIED
  alpha CDATA #IMPLIED
  image CDATA #IMPLIED
>

<!ELEMENT KeeperOnFloor PieceImageAlternates* >

<!ELEMENT LeftKeeperOnFloor PieceImageAlternates* >

<!ELEMENT RightKeeperOnFloor PieceImageAlternates* >

<!ELEMENT UpKeeperOnFloor PieceImageAlternates* >

<!ELEMENT DownKeeperOnFloor PieceImageAlternates* >

<!ELEMENT KeeperOnDeadFloor PieceImageAlternates* >

<!ELEMENT LeftKeeperOnDeadFloor PieceImageAlternates* >

<!ELEMENT RightKeeperOnDeadFloor PieceImageAlternates* >

<!ELEMENT UpKeeperOnDeadFloor PieceImageAlternates* >

<!ELEMENT DownKeeperOnDeadFloor PieceImageAlternates* >

<!ELEMENT KeeperOnGoal PieceImageAlternates* >

<!ELEMENT LeftKeeperOnGoal PieceImageAlternates* >

<!ELEMENT RightKeeperOnGoal PieceImageAlternates* >

<!ELEMENT UpKeeperOnGoal PieceImageAlternates* >

<!ELEMENT DownKeeperOnGoal PieceImageAlternates* >

<!ELEMENT MovingKeeper PieceImageAlternates* >

<!ELEMENT LeftMovingKeeper PieceImageAlternates* >

<!ELEMENT RightMovingKeeper PieceImageAlternates* >

<!ELEMENT UpMovingKeeper PieceImageAlternates* >

<!ELEMENT DownMovingKeeper PieceImageAlternates* >

<!ELEMENT VirtualKeeper PieceImageAlternates >

<!ELEMENT LeftVirtualKeeper PieceImageAlternates >

<!ELEMENT RightVirtualKeeper PieceImageAlternates >

<!ELEMENT UpVirtualKeeper PieceImageAlternates >

<!ELEMENT DownVirtualKeeper PieceImageAlternates >

<!ELEMENT GemOnFloor PieceImageAlternates >

<!ELEMENT GemOnDeadFloor PieceImageAlternates >

<!ELEMENT GemOnGoal PieceImageAlternates >

<!ELEMENT MovingGem PieceImageAlternates >

<!ELEMENT Floor PieceImageAlternates >

<!ELEMENT DeadFloor PieceImageAlternates >

<!ELEMENT Goal PieceImageAlternates >

<!ELEMENT LeftArrow PieceImageAlternates* >

<!ELEMENT RightArrow PieceImageAlternates* >

<!ELEMENT UpArrow PieceImageAlternates* >

<!ELEMENT DownArrow PieceImageAlternates* >

<!ELEMENT Wall ( WallPieceAlternates* ) >

<!ELEMENT Outside ( WallPieceAlternates* ) >


<!ELEMENT PieceImage ( Effect?, Layer* ) >
<!ATTLIST PieceImage
  size CDATA #REQUIRED
  xoffset CDATA #IMPLIED
  yoffset CDATA #IMPLIED
>

<!ELEMENT Effect ( ( Move | RotateLeft | RotateRight | UTurn | HMirror | VMirror |
		     BlendRgb | BlendRgba | BlendAlpha | Colorize | Scale | Crop )* ) >

<!ELEMENT RotateLeft EMPTY>

<!ELEMENT RotateRight EMPTY>

<!ELEMENT UTurn EMPTY>

<!ELEMENT Move EMPTY>
<!ATTLIST Move
  xoffset CDATA #REQUIRED
  yoffset CDATA #REQUIRED
>

<!ELEMENT BlendRgb EMPTY >
<!ATTLIST BlendRgb
  factor CDATA #REQUIRED
  red CDATA #IMPLIED
  green CDATA #IMPLIED
  blue CDATA #IMPLIED
>

<!ELEMENT BlendRgba EMPTY >
<!ATTLIST BlendRgba
  factor CDATA #REQUIRED
  red CDATA #IMPLIED
  green CDATA #IMPLIED
  blue CDATA #IMPLIED
  alpha CDATA #IMPLIED
>

<!ELEMENT BlendAlpha EMPTY >
<!ATTLIST BlendAlpha
  factor CDATA #REQUIRED
  alpha CDATA #IMPLIED
>

<!ELEMENT Colorize EMPTY >
<!ATTLIST Colorize
  factor CDATA #REQUIRED
  red CDATA #IMPLIED
  green CDATA #IMPLIED
  blue CDATA #IMPLIED
  alpha CDATA #IMPLIED
>

<!ELEMENT Scale EMPTY>
<!ATTLIST Scale
  width CDATA #REQUIRED
  height CDATA #REQUIRED
>

<!ELEMENT Crop EMPTY>
<!ATTLIST Crop
  xoffset CDATA #IMPLIED
  yoffset CDATA #IMPLIED
  width CDATA #REQUIRED
  height CDATA #REQUIRED
>

<!ELEMENT Layer ( Effect? ) >
<!ATTLIST Layer
  red CDATA #IMPLIED
  green CDATA #IMPLIED
  blue CDATA #IMPLIED
  alpha CDATA #IMPLIED
  image CDATA #IMPLIED
>
<!ELEMENT PieceImageAlternates PieceImage+>
<!ATTLIST PieceImageAlternates
  upperleft (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
  upper (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
  upperright (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
  left (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
  right (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
  lowerleft (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
  lower (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
  lowerright (floor|goal|wall|nonfloor|nongoal|nonwall|all) "all"
>

<!ELEMENT WallPieceAlternates PieceImage+>
<!ATTLIST WallPieceAlternates
  upperleft (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
  upper (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
  upperright (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
  left (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
  right (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
  lowerleft (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
  lower (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
  lowerright (inside|outside|wall|noninside|nonoutside|nonwall|all) "all"
>

=== RalfSchmelter/EasySok/assets/abstract.xml
<!DOCTYPE EasySokTheme SYSTEM "easysoktheme.dtd">

<EasySokTheme name="Abstract" red="192" green="192" blue="192">
	<KeeperOnFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="160" green="160" blue="160" />
				<Layer image="@drawable/abstract_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnFloor>
	<KeeperOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="128" green="128" blue="128" />
				<Layer image="@drawable/abstract_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnDeadFloor>
	<KeeperOnGoal>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="160" green="160" blue="160" />
				<Layer image="@drawable/abstract_goal.png" />
				<Layer image="@drawable/abstract_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnGoal>
	<MovingKeeper>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/abstract_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</MovingKeeper>
	<VirtualKeeper>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/abstract_virtual_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</VirtualKeeper>
	<GemOnFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="160" green="160" blue="160" />
				<Layer image="@drawable/abstract_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnFloor>
	<GemOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="128" green="128" blue="128" />
				<Layer image="@drawable/abstract_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnDeadFloor>
	<GemOnGoal>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="160" green="160" blue="160" />
				<Layer image="@drawable/abstract_goal.png" />
				<Layer image="@drawable/abstract_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnGoal>
	<MovingGem>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/abstract_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</MovingGem>
	<Floor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="160" green="160" blue="160" />
			</PieceImage>
		</PieceImageAlternates>
	</Floor>
	<DeadFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="128" green="128" blue="128" />
			</PieceImage>
		</PieceImageAlternates>
	</DeadFloor>
	<Goal>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer red="160" green="160" blue="160" />
				<Layer image="@drawable/abstract_goal.png" />
			</PieceImage>
		</PieceImageAlternates>
	</Goal>
	<LeftArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/abstract_arrow.png">
					<Effect>
						<RotateLeft />
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</LeftArrow>
	<RightArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/abstract_arrow.png">
					<Effect>
						<RotateRight />
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</RightArrow>
	<UpArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/abstract_arrow.png" />
			</PieceImage>		
		</PieceImageAlternates>
	</UpArrow>
	<DownArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/abstract_arrow.png">
					<Effect>
						<UTurn />
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</DownArrow>
	<Wall>
		<WallPieceAlternates>
			<PieceImage size="128">
				<Layer red="64" green="64" blue="64" />
			</PieceImage>
		</WallPieceAlternates>
	</Wall>
	<Outside>
	</Outside>
</EasySokTheme>

=== RalfSchmelter/EasySok/assets/simple_balls.xml
<!DOCTYPE EasySokTheme SYSTEM "easysoktheme.dtd" [

<!ENTITY Floor '<Layer red="160" green="160" blue="160" />'>
<!ENTITY DeadFloor '<Layer red="128" green="128" blue="128" />'>
<!ENTITY Goal1 '<Layer red="64" green="160" blue="64" />'>
<!ENTITY Goal2 '<Layer red="64" green="152" blue="64" />'>
<!ENTITY Keeper '<Layer image="@drawable/simple_balls_ball.png">
		 <Effect><Colorize red="240" green="64" blue="64" factor="1.2" /></Effect></Layer>'>
<!ENTITY VirtualKeeper '<Layer image="@drawable/simple_balls_ball.png">
			<Effect><Colorize red="255" green="160" blue="160" factor="1.0" /></Effect></Layer>'>
<!ENTITY Gem '<Layer image="@drawable/simple_balls_ball.png">
	      <Effect><Colorize red="255" green="255" blue="64" factor="1.0" /></Effect></Layer>'>
<!ENTITY ArrowColor '<Colorize red="224" green="224" blue="64" factor="1.0" />'>
<!ENTITY WallColor '<Colorize red="160" green="160" blue="255" factor="1.0" />'>
]>

<EasySokTheme name="SimpleBalls" red="102" green="102" blue="102">
	<KeeperOnFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Floor;
				&Keeper;
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnFloor>
	<KeeperOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				&DeadFloor;
				&Keeper;
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnDeadFloor>
	<KeeperOnGoal>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Goal1;
				&Keeper;
			</PieceImage>
			<PieceImage size="96">
				&Goal2;
				&Keeper;
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnGoal>
	<MovingKeeper>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Keeper;
			</PieceImage>
		</PieceImageAlternates>
	</MovingKeeper>
	<VirtualKeeper>
		<PieceImageAlternates>
			<PieceImage size="96">
				&VirtualKeeper;
			</PieceImage>
		</PieceImageAlternates>
	</VirtualKeeper>
	<GemOnFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Floor;
				&Gem;
			</PieceImage>
		</PieceImageAlternates>
	</GemOnFloor>
	<GemOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				&DeadFloor;
				&Gem;
			</PieceImage>
		</PieceImageAlternates>
	</GemOnDeadFloor>
	<GemOnGoal>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Goal1;
				&Gem;
			</PieceImage>
			<PieceImage size="96">
				&Goal2;
				&Gem;
			</PieceImage>
		</PieceImageAlternates>
	</GemOnGoal>
	<MovingGem>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Gem;
			</PieceImage>
		</PieceImageAlternates>
	</MovingGem>
	<Floor>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Floor;
			</PieceImage>
		</PieceImageAlternates>
	</Floor>
	<DeadFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				&DeadFloor;
			</PieceImage>
		</PieceImageAlternates>
	</DeadFloor>
	<Goal>
		<PieceImageAlternates>
			<PieceImage size="96">
				&Goal1;
			</PieceImage>
			<PieceImage size="96">
				&Goal2;
			</PieceImage>
		</PieceImageAlternates>
	</Goal>
	<LeftArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<RotateLeft />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</LeftArrow>
	<RightArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<RotateLeft />
						<HMirror />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</RightArrow>
	<UpArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<Move yoffset="2" />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</UpArrow>
	<DownArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<VMirror />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</DownArrow>
	<Wall>
		<WallPieceAlternates>
			<PieceImage size="96">
				<Layer red="114" green="114" blue="170" />		
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates upper="nonwall" >
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="0" yoffset="0" width="96" height="20" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall3.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates lower="nonwall" >
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="0" yoffset="76" width="96" height="20" />
					<Move yoffset="76" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall3.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" >
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="0" yoffset="0" width="20" height="96" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall4.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates right="nonwall" >
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="76" yoffset="0" width="20" height="96" />
					<Move xoffset="76" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall4.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" upper="nonwall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="0" yoffset="0" width="20" height="20" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall1.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates right="nonwall" upper="nonwall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="76" yoffset="0" width="20" height="20" />
					<Move xoffset="76" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall1.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates right="nonwall" lower="nonwall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="76" yoffset="76" width="20" height="20" />
					<Move xoffset="76" yoffset="76"/>
				</Effect>
				<Layer image="@drawable/simple_balls_wall1.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" lower="nonwall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="0" yoffset="76" width="20" height="20" />
					<Move xoffset="0" yoffset="76"/>
				</Effect>
				<Layer image="@drawable/simple_balls_wall1.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" upperleft="nonwall" upper="wall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="0" yoffset="0" width="20" height="20" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall2.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates right="wall" upperright="nonwall" upper="wall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="76" yoffset="0" width="20" height="20" />
					<Move xoffset="76" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall2.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" lowerleft="nonwall" lower="wall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="0" yoffset="76" width="20" height="20" />
					<Move yoffset="76" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall2.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates right="wall" lowerright="nonwall" lower="wall">
			<PieceImage size="96">
				<Effect>
					&WallColor;
					<Crop xoffset="76" yoffset="76" width="20" height="20" />
					<Move xoffset="76" yoffset="76" />
				</Effect>
				<Layer image="@drawable/simple_balls_wall2.png" />
			</PieceImage>
		</WallPieceAlternates>
	</Wall>
	<Outside>
	</Outside>
</EasySokTheme>

=== RalfSchmelter/EasySok/assets/text.xml
<!DOCTYPE EasySokTheme SYSTEM "easysoktheme.dtd">

<EasySokTheme name="Text" red="255" green="255" blue="255">
	<KeeperOnFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnFloor>
	<KeeperOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnDeadFloor>
	<KeeperOnGoal>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_keeper_on_goal.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnGoal>
	<MovingKeeper>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</MovingKeeper>
	<VirtualKeeper>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_virtual_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</VirtualKeeper>
	<GemOnFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnFloor>
	<GemOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnDeadFloor>
	<GemOnGoal>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_gem_on_goal.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnGoal>
	<MovingGem>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</MovingGem>
	<Floor>
		<PieceImageAlternates>
			<PieceImage size="128" />
		</PieceImageAlternates>
	</Floor>
	<DeadFloor>
		<PieceImageAlternates>
			<PieceImage size="128" />
		</PieceImageAlternates>
	</DeadFloor>
	<Goal>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_goal.png" />
			</PieceImage>
		</PieceImageAlternates>
	</Goal>
	<LeftArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
			</PieceImage>		
		</PieceImageAlternates>
	</LeftArrow>
	<RightArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
			</PieceImage>		
		</PieceImageAlternates>
	</RightArrow>
	<UpArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
			</PieceImage>		
		</PieceImageAlternates>
	</UpArrow>
	<DownArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
			</PieceImage>		
		</PieceImageAlternates>
	</DownArrow>
	<Wall>
		<WallPieceAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/text_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
	</Wall>
	<Outside>
	</Outside>
</EasySokTheme>

=== RalfSchmelter/EasySok/res/themes/xsokoban.xml
<!DOCTYPE EasySokTheme SYSTEM "easysoktheme.dtd" [

<!ENTITY ArrowColor '<Colorize red="128" green="128" blue="224" factor="1.0" />'>
<!ENTITY WallColor '<Colorize red="192" green="128" blue="96" factor="1.0" />'>

]>

<EasySokTheme name="XSokoban" red="102" green="102" blue="102">
	<KeeperOnFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnFloor>
	<KeeperOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_keeper_on_dead.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnDeadFloor>
	<KeeperOnGoal>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_keeper_on_goal.png" />
			</PieceImage>
		</PieceImageAlternates>
	</KeeperOnGoal>
	<MovingKeeper>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_moving_keeper.png" />
			</PieceImage>
		</PieceImageAlternates>
	</MovingKeeper>
	<VirtualKeeper>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_moving_keeper.png">
					<Effect>
						<BlendRgb factor="0.3" />
					</Effect>
				</Layer>
			</PieceImage>
		</PieceImageAlternates>
	</VirtualKeeper>
	<GemOnFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnFloor>
	<GemOnDeadFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_gem_on_dead.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnDeadFloor>
	<GemOnGoal>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_gem_on_goal.png" />
			</PieceImage>
		</PieceImageAlternates>
	</GemOnGoal>
	<MovingGem>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_moving_gem.png" />
			</PieceImage>
		</PieceImageAlternates>
	</MovingGem>
	<Floor>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_floor.png" />
			</PieceImage>
		</PieceImageAlternates>
	</Floor>
	<DeadFloor>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_dead_floor.png" />
			</PieceImage>
		</PieceImageAlternates>
	</DeadFloor>
	<Goal>
		<PieceImageAlternates>
			<PieceImage size="96">
				<Layer image="@drawable/xsokoban_goal.png" />
			</PieceImage>
		</PieceImageAlternates>
	</Goal>
	<LeftArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<RotateLeft />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</LeftArrow>
	<RightArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<RotateLeft />
						<HMirror />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</RightArrow>
	<UpArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<Move yoffset="2" />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</UpArrow>
	<DownArrow>
		<PieceImageAlternates>
			<PieceImage size="128">
				<Layer image="@drawable/common_arrow.png">
					<Effect>
						<VMirror />
						&ArrowColor;
					</Effect>
				</Layer>
			</PieceImage>		
		</PieceImageAlternates>
	</DownArrow>
	<Wall>
		<WallPieceAlternates left="nonwall" right="nonwall" upper="nonwall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor;
				</Effect>
				<Layer image="@drawable/xsokoban_eeee_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" right="nonwall" upper="wall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor;
				</Effect>
				<Layer image="@drawable/xsokoban_weee_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="nonwall" upper="nonwall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_ewee_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="nonwall" upper="wall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_wwee_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" right="wall" upper="nonwall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_eewe_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" right="wall" upper="wall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_wewe_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="wall" upper="nonwall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_ewwe_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="wall" upper="wall" lower="nonwall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_wwwe_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" right="nonwall" upper="nonwall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_eeew_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" right="nonwall" upper="wall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_weew_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="nonwall" upper="nonwall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_ewew_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="nonwall" upper="wall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_wwew_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" right="wall" upper="nonwall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_eeww_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="nonwall" right="wall" upper="wall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_weww_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="wall" upper="nonwall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_ewww_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
		<WallPieceAlternates left="wall" right="wall" upper="wall" lower="wall">
			<PieceImage size="128">
				<Effect>
					&WallColor; 
				</Effect>
				<Layer image="@drawable/xsokoban_wwwww_wall.png" />
			</PieceImage>
		</WallPieceAlternates>
	</Wall>
	<Outside>
	</Outside>
</EasySokTheme>
